version: '3.8'

services:
  db:
    build:
      context: ./docker/mysql/
    image: challange_db
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=codeeducation
      - MYSQL_DATABASE=codeeducation
    networks:
      - internal_net
    tty: true
    restart: always
    volumes:
      # - db_volume:/var/lib/mysql
      - ./docker/mysql/data:/var/lib/mysql

networks:
  internal_net:
    driver: bridge

# volumes:
  # db_volume: