version: '3.8'

services:
  app:
    build:
      context: ./docker/app/
    container_name: app
    image: challange_app
    networks:
      - internal_net
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: node index.js

  db:
    build:
      context: ./docker/mysql/
    image: challange_db
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=codeeducation
      - MYSQL_DATABASE=codeeducation
    networks:
      - internal_net
    tty: true
    restart: always
    volumes:
      # - db_volume:/var/lib/mysql
      - ./docker/mysql/data:/var/lib/mysql

networks:
  internal_net:
    driver: bridge

# volumes:
  # db_volume: